# Generated by Django 6.0 on 2025-12-29 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gaming', 'Gaming'), ('laptop', 'Laptop'), ('pc', 'PC'), ('celular', 'Celular'), ('tablet', 'Tablet'), ('accesorio', 'Accesorio'), ('ssd', 'SSD'), ('ram', 'RAM')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='auth_app.user')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='auth_app.user')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=100, unique=True)),
                ('name_product', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('VENDIDO', 'Vendido')], default='ACTIVO', max_length=10)),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='auth_app.user')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='auth_app.tag')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
