# Generated by Django 6.0 on 2025-12-29 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_tag_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='seller',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='auth_app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='vendor',
            field=models.ForeignKey(default=1, limit_choices_to={'is_vendor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='auth_app.user'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
