# Generated by Django 5.2.6 on 2025-12-25 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gaming', 'Gaming'), ('laptop', 'Laptop'), ('pc', 'PC'), ('celular', 'Celular'), ('tablet', 'Tablet'), ('accesorio', 'Accesorio'), ('ssd', 'SSD'), ('ram', 'RAM')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='auth_app.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='auth_app.tag'),
        ),
    ]
