# Generated by Django 5.2.6 on 2026-01-06 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_review_buyer_remove_review_seller_review_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(limit_choices_to={'is_vendor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='auth_app.user')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
