# Generated by Django 5.2.6 on 2025-12-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_tag_alter_product_vendor_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
