# Generated by Django 5.2.6 on 2026-01-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
