# Generated by Django 5.2.6 on 2025-12-29 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_rename_isvendor_user_is_vendor_remove_user_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='auth_app.user'),
        ),
    ]
