# Generated by Django 5.2.6 on 2026-01-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
